apiVersion: v1
kind: Service
metadata:
  namespace: frontend
  name: frontend-service

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: frontend
    type: frontend
