apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: frontend
  labels:
    app: frontend
    tier: frontend

spec:
  containers:
    - name: nginx
      image: nginx
    - name: busybox
      image: busybox
