apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mealie
  name: mealie-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: mealie
