apiVersion: v1
kind: Service
metadata:
  namespace: mealie
  name: mealie-service
spec:
  type: NodePort
  selector:
    app: mealie
  ports:
    - port: 8000
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 9000
      nodePort: 32000
