- name: Basic ubuntu install
  hosts: local  
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
    
    - name: install apt packages
      apt:
        name: "{{ packages }}"
        state: present
        install_recommends: yes
