apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
        type: frontend
    spec:
      containers:
        - name: nginx-containers
          image: nginx

  replicas: 3
